version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: candles
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - 5432:5432
  candles:
    build: .
    command: >
      sh -c "
             go run candles.go -vv -c ./examples/cfg.ini adm initdb
             go run candles.go -vv -c ./examples/cfg.ini srv"
    volumes:
      - .:/go/src/app
    restart: on-failure
    depends_on:
      - db
    links:
      - db
