// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package models

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type tickerTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *tickerTableType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("tickers").
func (v *tickerTableType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *tickerTableType) Columns() []string {
	return []string{"id", "label"}
}

// NewStruct makes a new struct for that view or table.
func (v *tickerTableType) NewStruct() reform.Struct {
	return new(Ticker)
}

// NewRecord makes a new record for that table.
func (v *tickerTableType) NewRecord() reform.Record {
	return new(Ticker)
}

// PKColumnIndex returns an index of primary key column for that table in SQL database.
func (v *tickerTableType) PKColumnIndex() uint {
	return uint(v.s.PKFieldIndex)
}

// TickerTable represents tickers view or table in SQL database.
var TickerTable = &tickerTableType{
	s: parse.StructInfo{Type: "Ticker", SQLSchema: "", SQLName: "tickers", Fields: []parse.FieldInfo{{Name: "ID", Type: "int64", Column: "id"}, {Name: "Label", Type: "string", Column: "label"}}, PKFieldIndex: 0},
	z: new(Ticker).Values(),
}

// String returns a string representation of this struct or record.
func (s Ticker) String() string {
	res := make([]string, 2)
	res[0] = "ID: " + reform.Inspect(s.ID, true)
	res[1] = "Label: " + reform.Inspect(s.Label, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *Ticker) Values() []interface{} {
	return []interface{}{
		s.ID,
		s.Label,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *Ticker) Pointers() []interface{} {
	return []interface{}{
		&s.ID,
		&s.Label,
	}
}

// View returns View object for that struct.
func (s *Ticker) View() reform.View {
	return TickerTable
}

// Table returns Table object for that record.
func (s *Ticker) Table() reform.Table {
	return TickerTable
}

// PKValue returns a value of primary key for that record.
// Returned interface{} value is never untyped nil.
func (s *Ticker) PKValue() interface{} {
	return s.ID
}

// PKPointer returns a pointer to primary key field for that record.
// Returned interface{} value is never untyped nil.
func (s *Ticker) PKPointer() interface{} {
	return &s.ID
}

// HasPK returns true if record has non-zero primary key set, false otherwise.
func (s *Ticker) HasPK() bool {
	return s.ID != TickerTable.z[TickerTable.s.PKFieldIndex]
}

// SetPK sets record primary key.
func (s *Ticker) SetPK(pk interface{}) {
	if i64, ok := pk.(int64); ok {
		s.ID = int64(i64)
	} else {
		s.ID = pk.(int64)
	}
}

// check interfaces
var (
	_ reform.View   = TickerTable
	_ reform.Struct = (*Ticker)(nil)
	_ reform.Table  = TickerTable
	_ reform.Record = (*Ticker)(nil)
	_ fmt.Stringer  = (*Ticker)(nil)
)

func init() {
	parse.AssertUpToDate(&TickerTable.s, new(Ticker))
}
